---
env:
  jest: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - prettier
ignorePatterns:
  - jest.config.js
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - tsconfig.json
    - tsconfig.eslint.json
  sourceType: module
plugins:
  - '@typescript-eslint'
root: true
rules:
  '@typescript-eslint/explicit-module-boundary-types':
    - off
  '@typescript-eslint/no-empty-interface':
    - off
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
  class-methods-use-this:
    - off
  import/extensions:
    - error
    - always
    - ignorePackages: true
  import/prefer-default-export:
    - off
